[versions]
node = "v16.14.0" # You can use any Node and NPM Version
# You can also specify the platform:
# node = { version = "v16.14.0", platform = "darwin-arm64" } 

[[task]]
name = "setup"
command = "npm i"

[[task]]
name = "dev"
command = "npm run dev"

[[task]]
name = "build"
command = "npm run build"

[[task]]
name = "version"
command = "node --version"
