[versions]
node = "v16.14.0" # You can use any Node and NPM Version
# You can also specify the platform:
# node = { version = "v16.14.0", platform = "darwin-arm64" } 

[tasks.setup]
command = "npm i"

[task.dev]
command = "npm run dev"

[tasks.build]
command = "npm run build"

[tasks.version]
command = "node --version"
