[versions]
node = "v16.14.0"
python = "3.9.9"

[tasks.setup]
command = '''
npm install
pip3 install -r requirements.txt
'''

[tasks.frontend-dev]
command = "npm run dev"

[tasks.backend-dev]
command = "python3 app.py"

[tasks.build]
command = "npm run build"
